version: "3.9"

services:
  nginx:
    build: .
    container_name: school_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - webnet

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    user: root
    command: --cleanup --interval 300 school_nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
