version: "3.9"

services:
  nginx:
    build: .
    container_name: school_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Mount static site
      - ./site:/usr/share/nginx/html:ro
      # Mount site-specific config (instead of replacing nginx.conf)
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --interval 300 school_nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # profiles: ["prod"]
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
